version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile.fpm
    container_name: php-fpm
    volumes:
      - .:/var/www
    networks:
      - central_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - central_network

  postgres:
    image: postgres:17
    container_name: postgres_appdaf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passer
      POSTGRES_DB: appdaf
    ports:
      - "5433:5432"
    volumes:
      - pg_data_appdaf:/var/lib/postgresql/data
    networks:
      - central_network

volumes:
  pg_data_appdaf:

networks:
  central_network:
    driver: bridge
