services:
  - type: web
    name: appdaf
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: appdaf-db
          property: connectionString
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false

databases:
  - name: appdaf-db
    databaseName: appdafdb
    user: appdaf
    plan: free