# docker/php-fpm/Dockerfile.fpm

FROM php:8.2-fpm

# Installer extensions PHP nécessaires
RUN apt-get update && apt-get install -y \
    libpq-dev \
    unzip \
    zip \
    git \
    && docker-php-ext-install pdo pdo_pgsql

# Installer Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

# Copier les fichiers de l’application
COPY . /var/www

# Donner les bons droits (si besoin)
RUN chown -R www-data:www-data /var/www

# EXPOSE 9000
